### ISSUE TITLE
Haxe 4.2 deprecates Std.is resulting in build warnings

### ISSUE THREAD

**Issue by martijndeb** [vegardit/haxe-strings#10]
The following error occurs in my project which has a dependency on haxe-strings by referral of another library;

/usr/share/haxe/lib/haxe-strings/6,0,3/src/hx/strings/collection/StringMap.hx:72: characters 11-60 : Warning : Std.is is deprecated. Use Std.isOfType instead.
/usr/share/haxe/lib/haxe-strings/6,0,3/src/hx/strings/collection/StringMap.hx:77: characters 11-62 : Warning : Std.is is deprecated. Use Std.isOfType instead.

This happens on Haxe version 4.2.1, and I think it's been deprecated since 4.2, so relatively close :).

**Comment by martijndeb** [comment]
Small addition; The other library is haxe-files, I think this deprecation error might cause my other problem there.

When using the following code there:
`		var d:Dir = Dir.of( "." );
		var list:Array<File> =  d.findFiles( myPath );
`

I get zero results, whereas in previous versions this would yield the two files in the same folder.

**Comment by sebthom** [comment]
Thanks for reporting. I am preparing a new release.

**Comment by sebthom** [comment]
6.0.4 is released
