### ISSUE TITLE
Other dictionaries

### ISSUE THREAD

**Issue by hoseyjoe** [vegardit/haxe-strings#3]
Are the dictionaries in a well known format?  Is there a way to find other dictionaries?

**Comment by sebthom** [comment]
Hi Joe, I am not aware of other pre-trained dictionaries. But it should be relatively simply to train your own ones, have a look at the code example at https://github.com/vegardit/haxe-strings#spell-checker

You may have to create your own DictionaryTrainer for languages with special characters, you can take the German one as an example: https://github.com/vegardit/haxe-strings/blob/master/src/hx/strings/spelling/trainer/GermanDictionaryTrainer.hx
