### ISSUE TITLE
haxe.Utf8 is deprecated. Use UnicodeString instead.

### ISSUE THREAD

**Issue by tjrhodes** [vegardit/haxe-strings#4]
Hey,

In haxe 4.0.2, this affects both Char.hx and Strings.hx.

Char.hx: line 626, Strings.hx: lines 749, 789.

Cheers, Tom.

**Comment by melMass** [comment]
Came to file the same issue ;)

**Comment by sebthom** [comment]
I released version 5.2.4. Please check if this solves your issue.

I can't fully remove haxe.Utf8, because currently UnicodeString misses an alternative to haxe.Utf8#addChar(int). Also for now I want to continue support Haxe 3.4.

**Comment by tynrare** [comment]
`/lib/haxe/haxe-strings/5,2,4/src/hx/strings/collection/OrderedStringMap.hx:158: characters 9-20 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.`

Same.

**Comment by tynrare** [comment]
Me vs common sense: 1:0
I build code that uses this dependency in another process, and than execute this build by `Sys.command` so i don't see warnings:D
```haxe
/**
 * This class executes serve build process to:
 * 1. Avoid build warns (build/serve.n is DEV process so it doesn't really matter)
 * 2. Execute serve process directly from ci `haxe serve.hxml`
 */
class ServeExecutor {
    static public function main():Void {
        var build = new sys.io.Process("haxe", ["maintenance/build/build-serve.hxml"]);
        var buildCode = build.exitCode();
        if(buildCode != 0) {
            //Yep. Rerun in again so i can see why it fall
            Sys.command("haxe", ["maintenance/build/build-serve.hxml"]);
            //But use OLD code
            Sys.exit(buildCode);
        }
        Sys.command("neko", ["build/serve.n"]);
    }
}
```

**Comment by sebthom** [comment]
haxe-strings 6.0.0 released.
