### ISSUE TITLE
untyped __js__ is deprecated, use js.Syntax.code instead

### ISSUE THREAD

**Issue by remiX-** [vegardit/haxe-strings#8]
Hi :)

I'm opening this now as from haxe 4.1.2 (or might be 4.1.0), any use of `untyped __js__` logs a warning to change to `js.Syntax.code`.

`...\.haxelib\haxe-strings/6,0,1/src/hx/strings/internal/OS.hx:24: characters 37-43 : Warning : __js__ is deprecated, use js.Syntax.code instead`

Thanks!

**Comment by sebthom** [comment]
@remiX- thanks for reporting. I'll work in this in the coming days.
